import assert from 'node:assert/strict';
import { createServer } from 'vite';
const storage = new Map();
globalThis.localStorage = { getItem: k => storage.get(k) ?? null, setItem: (k,v) => storage.set(k,v), removeItem: k => storage.delete(k) };
globalThis.window = { localStorage };
const server = await createServer({ server: { middlewareMode: true, hmr: false, ws: false }, appType: 'custom' });
try {
  const { ledgerTransactions, monthlyExpenditure, reconcileProjects } = await server.ssrLoadModule('/src/lib/financeLedger.ts');
  const { deadlineState } = await server.ssrLoadModule('/src/components/common/DeadlineBadge.tsx');
  const { verifiedFundReports } = await server.ssrLoadModule('/src/lib/verifiedFundReports.ts');
  const { pendingWork } = await server.ssrLoadModule('/src/lib/pendingWork.ts');
  const { useStore } = await server.ssrLoadModule('/src/store/useStore.ts');
  useStore.getState().login('SUPERADMIN');
  const state = useStore.getState();
  const project = state.projects[0];
  const bill = { ...state.bills[0], id: 'B', projectId: project.id, status: 'APPROVED', submittedDate: '2026-01-01', netPayable: 1000 };
  const tx = (id,kind,amount,date,fields={}) => ({ id,projectId:project.id,kind,status:'VERIFIED',submittedAt:'2026-01-01',reference:id,fields:{amount:String(amount),transactionDate:date,billId:'B',...fields} });
  const records = [tx('R','RECEIPT',2000,'2026-01-01'),tx('P','PAYMENT',300,'2026-01-02'),tx('Q','PAYMENT',200,'2026-02-01'),tx('V','REVERSAL',300,'2026-03-01',{originalTransactionId:'P'}),{...tx('U','PAYMENT',900,'2026-01-03'),status:'PENDING'},tx('F','PAYMENT',500,'2027-01-01')];
  assert.deepEqual(ledgerTransactions(records,project.id,'2026-02-20').map(r=>r.id),['R','P','Q']);
  const projects = reconcileProjects([project],records,'2026-09-22');
  assert.equal(projects[0].amountSpent,200);
  assert.equal(projects[0].amountReleased,2000);
  const months = monthlyExpenditure(records,new Set([project.id]),'2026-09-22');
  assert.equal(months.length,12);
  assert.equal(months[0].month,'2025-10');
  assert.equal(months.at(-1).month,'2026-09');
  assert.equal(months.find(m=>m.month==='2026-03').amount,-300);
  assert.equal(months.find(m=>m.month==='2026-02').change,-100);
  assert.equal(months.reduce((n,m)=>n+m.amount,0),200);
  const testState = {...state,projects,controlRecords:records,bills:[bill],fundInstallments:[]};
  const reports = verifiedFundReports(testState,projects,'2026-09-22');
  assert.equal(reports.contractor.total,projects[0].amountSpent);
  assert.equal(reports.government.total,projects[0].amountReleased);
  assert.equal(reports.contractor.pending[0].netPayable,800);
  assert.ok(pendingWork(testState,'2026-09-22').some(t=>t.billId==='B' && t.tab==='finance'));
  assert.equal(deadlineState({...project,status:'ON_TRACK',plannedCompletionDate:'2026-09-25'},'2026-09-22').days,3);
  assert.equal(deadlineState({...project,status:'ON_TRACK',plannedCompletionDate:'2026-09-20'},'2026-09-22').label,'{{0}} days overdue');
  assert.equal(deadlineState({...project,status:'COMPLETED'},'2026-09-22').label,'Completed');
  console.log('Finance reconciliation, partial payment, reversal timing, 12-month series, pending bill and deadline tests passed.');
} finally { await server.close(); }
