import assert from 'node:assert/strict';
import { createServer } from 'vite';
globalThis.localStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {} };
globalThis.window = { localStorage };
const server = await createServer({server: {middlewareMode: true, hmr: false, ws: false}, appType: 'custom'});
try {
  const { useStore } = await server.ssrLoadModule('/src/store/useStore.ts');
  const { computeProjectScope } = await server.ssrLoadModule('/src/lib/projectScope.ts');
  const { inspectionAssignmentRoles, inspectionAccounts } = await server.ssrLoadModule('/src/lib/inspectionAccess.ts');
  const state = () => useStore.getState();
  state().login('DEPUTY_ENGINEER');
  const junior = state().currentUser;
  const appointmentInput = state().inspectionAppointments.find(a => junior.assignedProjectIds.includes(a.projectId));
  const appointment = state().requestAppointment({...appointmentInput, requestedBy: 'Old random name', requestedByRole: 'CONTRACTOR', remarks: 'Inspect readiness'});
  assert.equal(appointment.requestedBy, junior.name);
  assert.equal(appointment.requestedById, junior.id);
  state().scheduleAppointment(appointment.id, '2026-10-01', '10:00', 'Old random inspector');
  const scheduled = state().inspectionAppointments.find(a => a.id === appointment.id);
  assert.equal(scheduled.assignedInspector, junior.name);
  assert.equal(scheduled.assignedBy, junior.name);
  const project = computeProjectScope(junior, state().projects, state().contractors).projects[0];
  state().login('EXECUTIVE_ENGINEER', project.executiveEngineerId);
  const ee = state().currentUser;
  const other = { ...junior, id: 'TEST-JE', name: 'Second JE', assignedProjectIds: [project.id] };
  const outside = { ...junior, id: 'OUTSIDE-JE', assignedProjectIds: [] };
  useStore.setState({users: [...state().users, other, outside]});
  const input = {projectId: project.id, category: 'PLUMBING', scheduledDate: '2026-10-01', scheduledTime: '10:00', location: 'Ward B', scope: 'Pressure', assignedToId: junior.id, inspector: '', comments: ''};
  assert.deepEqual(inspectionAssignmentRoles(ee), ['DEPUTY_ENGINEER']);
  assert.deepEqual(inspectionAssignmentRoles(junior), []);
  assert.throws(() => state().scheduleInspection({...input, assignedToId: outside.id}), /eligible/);
  const contractor = inspectionAccounts(state().users, state().projects, state().contractors).find(u => u.role === 'CONTRACTOR');
  assert.throws(() => state().scheduleInspection({...input, assignedToId: contractor.id}), /eligible/);
  const inspection = state().scheduleInspection(input);
  assert.equal(inspection.assignedToId, junior.id);
  assert.throws(() => state().assignInspection(inspection.id, other.id, ' '), /reason/);
  state().assignInspection(inspection.id, other.id, 'Site coverage');
  assert.equal(state().inspections.find(i => i.id === inspection.id).assignmentHistory.length, 2);
  useStore.setState({currentUser: junior});
  assert.throws(() => state().startInspection(inspection.id), /assigned Junior/);
  assert.throws(() => state().assignInspection(inspection.id, junior.id, 'Take over'), /Only EE/);
  useStore.setState({currentUser: other});
  state().startInspection(inspection.id);
  useStore.setState({currentUser: ee});
  assert.throws(() => state().assignInspection(inspection.id, junior.id, 'Move'), /scheduled or returned/);
  const sourceId = inspection.id;
  const defect = {id: 'DEFECT-A', projectId: project.id, sourceInspectionId: sourceId, category: 'PLUMBING', status: 'FIXED', description: 'Leak'};
  useStore.setState({defects: [...state().defects, defect, {...defect, id: 'DEFECT-B', status: 'REINSPECTION'}]});
  const reinspection = state().reinspect(defect.id);
  assert.equal(reinspection.sourceDefectId, defect.id);
  const items = [{id: 'test', requirement: 'Pressure', measurement: '3 bar', standard: '3 bar', result: 'PASS', evidence: '', remarks: ''}];
  useStore.setState({currentUser: other});
  state().startInspection(reinspection.id);
  state().setInspectionDocuments(reinspection.id, [{id: 'test-document', category: 'SUPPORTING', name: 'inspection.pdf', mimeType: 'application/pdf', size: 100}]);
  state().submitInspection(reinspection.id, items, 'PASS', 'Verified');
  useStore.setState({currentUser: ee, controlRecords: [...state().controlRecords, {id: 'quality-test', kind: 'QUALITY', status: 'VERIFIED', projectId: project.id, fields: {inspectionId: reinspection.id, result: 'PASS', defectId: 'DEFECT-B'}}]});
  assert.throws(() => state().reviewInspection(reinspection.id, 'APPROVE', ''), /reference this reinspection/);
  useStore.setState({controlRecords: state().controlRecords.map(r => r.id === 'quality-test' ? {...r, fields: {...r.fields, defectId: defect.id}} : r)});
  state().reviewInspection(reinspection.id, 'APPROVE', 'Accepted');
  assert.equal(state().defects.find(d => d.id === defect.id).status, 'CLOSED');
  assert.equal(state().defects.find(d => d.id === 'DEFECT-B').status, 'REINSPECTION');
  console.log('EE-to-JE allocation, project scope, reassignment history and operator permissions passed.');
} finally { await server.close(); }
