import assert from 'node:assert/strict';
import {createServer} from 'vite';
const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};globalThis.window={localStorage};
const evidence=new Map();globalThis.indexedDB={open:()=>{const req={};queueMicrotask(()=>{req.result={close(){},transaction:()=>({objectStore:()=>({get:id=>{const r={};queueMicrotask(()=>{r.result=evidence.get(id);r.onsuccess();});return r;}})})};req.onsuccess();});return req;}};
const server=await createServer({server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});
try{
 const {useStore}=await server.ssrLoadModule('/src/store/useStore.ts');
 const {measurementQuantity}=await server.ssrLoadModule('/src/lib/siteReports.ts');
 const {validateControl}=await server.ssrLoadModule('/src/lib/projectControls.ts');
 const {pendingWork}=await server.ssrLoadModule('/src/lib/pendingWork.ts');
 const s=()=>useStore.getState();s().login('SUPERADMIN');
 const project=s().projects[0];
 const je={...s().currentUser,id:'JE-TEST',role:'DEPUTY_ENGINEER',assignedProjectIds:[project.id]};
 const ee={...je,id:'EE-TEST',role:'EXECUTIVE_ENGINEER'};
 const item={id:'TEST-BOQ',projectId:project.id,item:'Concrete',unit:'m³',plannedQty:100,completedQty:0,rate:6000,category:'RCC'};
 useStore.setState({currentUser:je,boqItems:[...s().boqItems,item]});
 const blob=new Blob(['%PDF-1.7 report'],{type:'application/pdf'});evidence.set('PROOF',blob);
 const attachments=[{id:'PROOF',name:'test.pdf',mimeType:blob.type,size:blob.size,category:'SUPPORTING'}];
 const input={projectId:project.id,kind:'MEASUREMENT',category:'MEASUREMENT',reference:'MB-TEST-001',attachments,fields:{bookNumber:'MB-1',pageNumber:'1 / 1',measurementDate:'2026-09-20',boqItemId:item.id,location:'Ward A slab',method:'VOLUME',count:'1',length:'10',breadth:'5',depth:'.15',deduction:'0',quantity:'7.5',unit:'m³',rate:'6000'}};
 assert.equal(measurementQuantity(input.fields),7.5);
 assert.ok(Number.isNaN(measurementQuantity({...input.fields,depth:'Infinity'})));
 assert.throws(()=>validateControl(s(),{...input,fields:{...input.fields,quantity:'75'}}),/calculation/);
 assert.throws(()=>validateControl(s(),{...input,fields:{...input.fields,measurementDate:'2026-02-30'}}),/valid measurement date/);
 await s().submitControl(input);const mb=s().controlRecords.at(-1);
 assert.equal(mb.status,'PENDING');
 await assert.rejects(()=>s().submitControl({...input,reference:'DIFFERENT-REF'}),/already has an entry/);
 await assert.rejects(()=>s().reviewControl(mb.id,true,'Self review'),/authorized/);
 useStore.setState({currentUser:{...je,role:'SUPERADMIN'}});
 await assert.rejects(()=>s().reviewControl(mb.id,true,'Self review'),/independent/);
 useStore.setState({currentUser:ee});
 await s().reviewControl(mb.id,true,'Dimensions and signed evidence checked');
 assert.equal(s().controlRecords.find(r=>r.id===mb.id).status,'VERIFIED');
 useStore.setState({currentUser:je});
 const lab={projectId:project.id,kind:'MATERIAL_TEST',category:'MATERIAL_TEST',reference:'LAB-TEST-001',attachments,fields:{boqItemId:item.id,measurementId:mb.id,material:'Concrete',testName:'28-day cube strength',sampleReference:'BATCH-1',sampleDate:'2026-08-20',testDate:'2026-09-17',location:'Ward A slab',laboratory:'Test laboratory',standardVersion:'Contract test specification v1',acceptanceCriteria:'At least 30 MPa',resultValue:'22',resultUnit:'MPa',result:'FAIL'}};
 assert.throws(()=>validateControl(s(),{...lab,fields:{...lab.fields,testDate:'2026-08-19'}}),/Test dates/);
 assert.throws(()=>validateControl(s(),{...lab,fields:{...lab.fields,measurementId:'OTHER-PROJECT'}}),/same project/);
 assert.throws(()=>validateControl(s(),{...lab,fields:{...lab.fields,billId:'OTHER-BILL'}}),/bill from this project/);
 await s().submitControl(lab);const test=s().controlRecords.at(-1);
 useStore.setState({currentUser:ee});
 assert.ok(pendingWork(s(),'2026-09-27').some(r=>r.id===`control-${test.id}`&&r.tab==='quality'));
 await s().reviewControl(test.id,true,'Report accepted as evidence of failed material; corrective action required');
 assert.equal(s().controlRecords.find(r=>r.id===test.id).fields.result,'FAIL');
 assert.equal(s().controlRecords.find(r=>r.id===test.id).status,'VERIFIED');
 useStore.setState({currentUser:je});
 await s().submitControl({...lab,reference:'LAB-RETURNED'});const returned=s().controlRecords.at(-1);
 useStore.setState({currentUser:ee});await s().reviewControl(returned.id,false,'Missing laboratory seal');
 assert.equal(s().controlRecords.find(r=>r.id===returned.id).status,'REJECTED');
 useStore.setState({currentUser:{...je,assignedProjectIds:[]}});
 assert.throws(()=>validateControl(s(),{...lab,reference:'OUTSIDE'}),/authorized/);
 for(const role of ['CONTRACTOR','MINISTER','IT_ADMIN']){useStore.setState({currentUser:{...je,role,contractorId:project.contractorId}});assert.throws(()=>validateControl(s(),{...lab,reference:'ROLE-TEST'}),/assigned engineers|Read-only|authorized/);}
 console.log('Site reports: calculations, dates, duplicate MB entries, project scope, JE submission, independent review, failed test preservation, rejection and pending navigation passed.');
}finally{await server.close();}
